name = "uncle-sams-cart-events"
main = "workers/share-events.js"
compatibility_date = "2026-04-28"

[[d1_databases]]
binding = "DB"
database_name = "uncle-sams-cart-events"
database_id = "15727984-d61c-4df3-979d-f51bcfdadd3f"
